name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
      - name: Restore keystore
        run: |
          echo '${{secrets.RELEASE_KEYSTORE}}' > release.keystore.asc
          gpg -d --passphrase '${{secrets.RELEASE_KEYSTORE_PASSPHRASE}}' --batch release.keystore.asc > android/app/agendasus.keystore
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{secrets.RELEASE_KEYSTORE_PASSPHRASE}}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{secrets.RELEASE_KEYSTORE_PASSPHRASE}}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
